<a href="https://colab.research.google.com/github/SnSabu/Machine-Learning-Projects/blob/main/Webscraping_using_BeautifulSoup_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Webscraping Gas Prices


> *By Sneha Sabu*

In this notebook, average gas prices from each of the input zip codes are scraped from the Autoblog website. Here the BeautifulSoup library is used to extract information from the html page.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

#zipcodes = US_postal_codes["postal_code"].head(50).values.tolist()
zipcodes = [
'94591',
'94609',
'11040',
'17201',
'77375',
'85132',
'90010',
'75225',
'90814']

zip_price = []

all_gas_prices = [] # list to store all gas prices from all zipcodes

for zipcode in zipcodes:
    url = "https://www.autoblog.com/" + zipcode + "-gas-prices/"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    results = soup.find(id="shops-map")
    gasprice = results.find_all("li", class_="slab price")
    values = [float(item.find("data")["value"]) for item in gasprice]
    Avg_Price = sum(values)/len(values)
    all_gas_prices.append(Avg_Price)
    zip_price.append((zipcode,Avg_Price))
zip_price_df = pd.DataFrame(zip_price,columns=['Zip Code', 'Gas Price'])


#print(all_gas_prices)

zip_price_df

  Zip Code  Gas Price
0    94591      4.444
1    94609      4.795
2    11040      3.435
3    17201      3.818
4    77375      3.016
5    85132      3.454
6    90010      4.668
7    75225      3.297
8    90814      4.520